[build]
  base = "frontend/"
  publish = ".next"
  command = "npm run build"

[build.environment]
  NODE_VERSION = "18"
  NPM_FLAGS = "--legacy-peer-deps"

# Redirect all requests to Next.js for client-side routing
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

# API redirects (if using external backend)
[[redirects]]
  from = "/api/*"
  to = "https://portfolio-dashboard-backend.herokuapp.com/api/:splat"
  status = 200
  force = true

# Environment variables for different deploy contexts
[context.production]
  environment = { NEXT_PUBLIC_API_BASE_URL = "https://portfolio-dashboard-backend.herokuapp.com/api", NEXT_PUBLIC_REFRESH_INTERVAL = "15000" }

[context.deploy-preview]
  environment = { NEXT_PUBLIC_API_BASE_URL = "https://portfolio-dashboard-backend-staging.herokuapp.com/api", NEXT_PUBLIC_REFRESH_INTERVAL = "30000" }

[context.branch-deploy]
  environment = { NEXT_PUBLIC_API_BASE_URL = "https://portfolio-dashboard-backend-dev.herokuapp.com/api", NEXT_PUBLIC_REFRESH_INTERVAL = "60000" }

# Headers for security
[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"

# Cache static assets
[[headers]]
  for = "/static/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

# Functions directory (if using Netlify Functions for API)
[functions]
  directory = "netlify/functions"
